# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3a68077160fe627f3146bcb5818270387120ebed15c13d531301b4aa8aca9441ad64dccd8524207a4534bf217a042b39cf84ce124ed36aabf2933a5f9375d29

test:
  secret_key_base: e567ebf73a10c23cb1f47923ce162d47fac9b9fee3aeae6738fb2c0bd766a7473eaf5b48577e1cd30ecbc3d440b9e4bb146aa4f3820dee7d8992d6a6855bb228

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
